---
title           : "Sex and social class determined survival on the Titanic"
shorttitle      : "Survival on the Titanic"
date            : "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time(), '%d\\\\. %B %Y')`"

author: 
  - name        : Lina Aragon-Baquero
    affiliation : 1
  - name        : Kristen Bill
    affiliation : 2
  - name        : Leah D'Aloisio
    affiliation : 3  
  - name        : Jack Goldman
    affiliation : 4  
  - name        : Briar Hunter
    affiliation : "5,6"  

affiliation:
  - id          : 1
    institution : University of Waterloo
  - id          : 2
    institution : Wilfrid Laurier University 
  - id          : 3
    institution : University of British Columbia Okanagan
  - id          : 4
    institution : University of Toronto
  - id          : 5
    institution : Laurentian University
  - id          : 6
    institution : Toronto Zoo

output: prereg::cos_prereg
bibliography: references.bib
---

# Study Information

Sex and social class determined survival on the Titanic?

`r rmarkdown::metadata$title`

## Description

It is well known that survivorship upon the sinking of the Titanic was heavily influenced by sex and class of the individual. Previous studies reveal the role of sex and class was a strong predictor of survival due to policies and social/physical barriers put in place prioritizing first class and women/children @hall1986 @frey2010. This study seeks to replicate previous findings while also statistically testing the degree to which these variables influenced survival. Therefore, using an alternative dataset, we will run a mixed effects model to test the effects of class and sex on survival on the Titanic.

## Hypotheses

Similar to other studies done on Titanic survivorship data, we predict class and sex will have a strong impact on survivorship, with women/children and higher class passengers (i.e. first class) being more likely to survive than men or third class passengers.

# Design Plan

## Study type

This is a retrospective observation study based on data obtained from the historical event of the sinking of the Titanic.

## Blinding

Not applicable

## Study design

This study utilizes retrospective data from a one-time, natural event and thus data collection was constrained by availability of information gathered and documented from passengers and survivors at the time. On account of this being a one-time event with a defined number of people our design is a cross-sectional observation study.

To understand the driving factors of survival aboard the titanic, we will use a mixed effect model approach in which sex and class will be fixed factors and age a random factor: Survival \~ Class + Sex + (1\|Age).

## Randomization

Not applicable.

# Sampling Plan

## Existing data

As of the date of this submission, we have accessed and analyzed some of the data relevant to the research plan, including preliminary analysis of variables, calculation of descriptive statistics, and observation of data distributions.

## Explanation of existing data

The data we will use is a dataset retrieved from <https://github.com/paulhendricks/titanic>. The data provides information on the fate of passengers of the Titanic including variables such as class, age, sex, ticket fare, and nationality. This dataset is an array resulting from cross-tabulating 2201 observations. Prior to conducting our own analyses, we will not read any papers performing statistical analyses and thus remain unaware of any summary statistics on the data. We have only read prior articles using a different dataset to discuss effects of social class and sex on survival. These papers also gathered information based on interviews of the survivors following the event.

## Data collection procedures

```{=html}
<!-- Please describe the process by which you will collect your data. If you are using human subjects, this should include the population from which you obtain subjects, recruitment efforts, payment for participation, how subjects will be selected for eligibility from the initial pool (e.g. inclusion and exclusion rules), and your study timeline. For studies that donÍt include human subjects, include information about how you will collect samples, duration of data gathering efforts, source or location of samples, or batch numbers you will use.

The answer to this question requires a specific set of instructions so that another person could repeat the data collection procedures and recreate the study population. Alternatively, if the study population would be unable to be reproduced because it relies on a specific set of circumstances unlikely to be recreated (e.g., a community of people from a specific time and location), the criteria and methods for creating the group and the rationale for this unique set of subjects should be clear.

Example: Participants will be recruited through advertisements at local pastry shops. Participants will be paid $10 for agreeing to participate (raised to $30 if our sample size is not reached within 15 days of beginning recruitment). Participants must be at least 18 years old and be able to eat the ingredients of the pastries. -->
```
This study will use the publicly available titanic dataset found in R. The principal source for the data in this package is the Encyclopedia Titanica but a variety of researchers contributed to the datasets, including Eaton & Haas (1994) Titanic: Triumph and Tragedy, Patrick Stephens Ltd (<http://campus.lakeforest.edu/frank/FILES/MLFfiles/Bio150/Titanic/TitanicMETA.pdf> ). The study population we will use is not reproducible, as it relied on the specific circumstances of the Titanic sinking, which we hope never happens again. Comparative analyses, however, can be performed on similar events such as the sinking of the Lusitania @frey2010a, but the exact conditions are unlikely to be repeated.

## Sample size

```{=html}
<!-- Describe the sample size of your study. How many units will be analyzed in the study? This could be the number of people, birds, classrooms, plots, interactions, or countries included. If the units are not individuals, then describe the size requirements for each unit. If you are using a clustered or multilevel design, how many units are you collecting at each level of the analysis? For some studies, this will simply be the number of samples or the number of clusters. For others, this could be an expected range, minimum, or maximum number.

Example: Our target sample size is 280 participants. We will attempt to recruit up to 320, assuming that not all will complete the total task. -->
```
The sample size of our study will be based on available passenger data. The total sample size in the dataset is 1309 subjects. Since 263 passengers are missing information about their age, we will be using a sample size of 1046. 

## Sample size rationale

```{=html}
<!-- This could include a power analysis or an arbitrary constraint such as time, money, or personnel. This gives you an opportunity to specifically state how the sample size will be determined. A wide range of possible answers is acceptable; remember that transparency is more important than principled justifications. If you state any reason for a sample size upfront, it is better than stating no reason and leaving the reader to "fill in the blanks." Acceptable rationales include: a power analysis, an arbitrary number of subjects, or a number based on time or monetary constraints.

Example: We used the software program G*Power to conduct a power analysis. Our goal was to obtain .95 power to detect a medium effect size of .25 at the standard .05 alpha error probability. -->
```
Since these data are obtained from an historical event, we are constrained to the information made available to the public. The sample size in this dataset is not true to the total number of passengers and crew on board due to lack of records obtained prior to boarding the Titanic. Furthermore, not all information is provided for each passenger in the dataset, as certain details were only able to be obtained from the survivors. Since we are not adding observations from this historical event, we will not be doing a power analysis. After removing missing variables, we will use 1046 passengers from the dataset.

## Stopping rule

```{=html}
<!-- If your data collection procedures do not give you full control over your exact sample size, specify how you will decide when to terminate your data collection. 

You may specify a stopping rule based on p-values only in the specific case of sequential analyses with pre-specified checkpoints, alphas levels, and stopping rules. Unacceptable rationales include stopping based on p-values if checkpoints and stopping rules are not specified. If you have control over your sample size, then including a stopping rule is not necessary, though it must be clear in this question or a previous question how an exact sample size is attained.

Example: We will post participant sign-up slots by week on the preceding Friday night, with 20 spots posted per week. We will post 20 new slots each week if, on that Friday night, we are below 320 participants. -->
```
Not applicable

# Variables

<!-- In this section you can describe all variables (both manipulated and measured variables) that will later be used in your confirmatory analysis plan. In your analysis plan, you will have the opportunity to describe how each variable will be used. If you have variables which you are measuring for exploratory analyses, you are not required to list them, though you are permitted to do so. -->

## Manipulated variables

```{=html}
<!-- Describe all variables you plan to manipulate and the levels or treatment arms of each variable. This is not applicable to any observational study. For any experimental manipulation, you should give a precise definition of each manipulated variable. This must include a precise description of the levels at which each variable will be set, or a specific definition for each categorical treatment. For example, “loud or quiet,” should instead give either a precise decibel level or a means of recreating each level. 'Presence/absence' or 'positive/negative' is an acceptable description if the variable is precisely described.

Example: We manipulated the percentage of sugar by mass added to brownies. The four levels of this categorical variable are: 15%, 20%, 25%, or 40% cane sugar by mass. -->
```
Not applicable.

## Measured variables

```{=html}
<!-- Describe each variable that you will measure. This will include outcome measures, as well as any predictors or covariates that you will measure. You do not need to include any variables that you plan on collecting if they are not going to be included in the confirmatory analyses of this study.

Observational studies and meta-analyses will include only measured variables. As with the previous questions, the answers here must be precise. For example, 'intelligence,' 'accuracy,' 'aggression,' and 'color' are too vague. Acceptable alternatives could be 'IQ as measured by Wechsler Adult Intelligence Scale' 'percent correct,' 'number of threat displays,' and 'percent reflectance at 400 nm.'

Example: The single outcome variable will be the perceived tastiness of the single brownie each participant will eat. We will measure this by asking participants ‘How much did you enjoy eating the brownie’ (on a scale of 1-7, 1 being 'not at all', 7 being 'a great deal') and 'How good did the brownie taste' (on a scale of 1-7, 1 being 'very bad', 7 being 'very good'). -->
```
**The measured variables will be:**

-   Passenger class on the boat = (1 = 1st; 2 = 2nd; 3 = 3rd) 

-   Survival = (0 = No; 1 = Yes) 

-   Sex (those of uknown sex were added to male category)

-   Age

**Other variables provided in the dataset, but will not be included in this confirmatory analysis are:**

-   Number of family members = number of siblings/spouses and parents/children on board 

-   fare = Passenger Fare in British pounds

-   Boat number = Which lifeboat a passenger was on

-   Home/Destination = Destination of travels

## Indices

```{=html}
<!-- If any measurements are  going to be combined into an index (or even a mean), what measures will you use and how will they be combined? Include either a formula or a precise description of your method. If your are using a more complicated statistical method to combine measures (e.g. a factor analysis), you can note that here but describe the exact method in the analysis plan section.

If you are using multiple pieces of data to construct a single variable, how will this occur? Both the data that are included and the formula or weights for each measure must be specified. Standard summary statistics, such as "means" do not require a formula, though more complicated indices require either the exact formula or, if it is an established index in the field, the index must be unambiguously defined. For example, "biodiversity index" is too broad, whereas "Shannon’s biodiversity index" is appropriate.

Example: We will take the mean of the two questions above to create a single measure of 'brownie enjoyment.'  -->
```
To understand the summary statistics of the Titanic data, means will be extracted from the raw data. No other indices will be used for these data. Estimated marginal means will be used for multiple comparisons of simple logistic regressions.

# Analysis Plan

```{=html}
<!-- You may describe one or more confirmatory analysis in this preregistration. Please remember that all analyses specified below must be reported in the final article, and any additional analyses must be noted as exploratory or hypothesis generating.

A confirmatory analysis plan must state up front which variables are predictors (independent) and which are the outcomes (dependent), otherwise it is an exploratory analysis. You are allowed to describe any exploratory work here, but a clear confirmatory analysis is required. -->
```
To understand how social class and gender (independent) drive survivorship (dependent) on the Titanic, we will use general mixed effect models with age as a random effect in the model (R package: lme4). Interactions between gender and social class will also be explored to assess whether the interaction of the two variables are driving the outcome.

## Statistical models

```{=html}
<!-- What statistical model will you use to test each hypothesis? Please include the type of model (e.g. ANOVA, multiple regression, SEM, etc) and the specification of the model (this includes each variable that will be included as predictors, outcomes, or covariates). Please specify any interactions, subgroup analyses, pairwise or complex contrasts, or follow-up tests from omnibus tests. If you plan on using any positive controls, negative controls, or manipulation checks you may mention that here. Remember that any test not included here must be noted as an exploratory test in your final article.

This is perhaps the most important and most complicated question within the preregistration. As with all of the other questions, the key is to provide a specific recipe for analyzing the collected data. Ask yourself: is enough detail provided to run the same analysis again with the information provided by the user? Be aware for instances where the statistical models appear specific, but actually leave openings for the precise test. See the following examples:

- If someone specifies a 2x3 ANOVA with both factors within subjects, there is still flexibility with the various types of ANOVAs that could be run. Either a repeated measures ANOVA (RMANOVA) or a multivariate ANOVA (MANOVA) could be used for that design, which are two different tests. 
- If you are going to perform a sequential analysis and check after 50, 100, and 150 samples, you must also specify the p-values you’ll test against at those three points.

Example:  We will use a one-way between subjects ANOVA to analyze our results. The manipulated, categorical independent variable is 'sugar' whereas the dependent variable is our taste index. -->
```
To understand how social class and gender drive survivorship on the Titanic, we will use generalized mixed effect models with age as a random effect in the model (R package: lme4). Interactions between gender and social class will also be explored to assess whether the interaction of the two variables are driving the outcome. Multicollinearity will also be assessed using variable inflation factor (VIF) (R package: car). Chi-squared test for comparisons of models will be used to test the differences among models. Estimated marginal means (R package: emmeans) with Bonferroni adjustments will be used for multiple comparisons for simple logistic multiple regression models. Model prediction assessment will be done using confusion matrices. 

## Transformations

```{=html}
<!-- If you plan on transforming, centering, recoding the data, or will require a coding scheme for categorical variables, please describe that process. If any categorical predictors are included in a regression, indicate how those variables will be coded (e.g. dummy coding, summation coding, etc.) and what the reference category will be.

Example: The "Effect of sugar on brownie tastiness" does not require any additional transformations. However, if it were using a regression analysis and each level of sweet had been categorically described (e.g. not sweet, somewhat sweet, sweet, and very sweet), 'sweet' could be dummy coded with 'not sweet' as the reference category. -->
```
No transformations will be used for these data unless transformations are needed to meet assumptions. There are several variables that are binary and will be coded. The dependent variable survived will be coded as "yes" and "no". Gender, which is a predictor variable, will be coded as "male" or "female."

## Inference criteria


## Data exclusion

Passengers who did not have their age documented in the dataset will be excluded from the study. Outliers will be included in the analysis. 

## Missing data

Passengers who did not have their age in the dataset were automatically excluded from the analysis. 

## Exploratory analyses (optional)

```{r}
library(tidyverse) # data wrangling and visualization
library(sjPlot)    # to visualizing mixed-effects models
library(lme4)      # "golden standard" for mixed-effects modelling in R (no p-values)
library(lmerTest)  # p-values for MEMs based on the Satterthwaite approximation
library(emmeans)   # post-hoc analysis
library(knitr)     # beautifying tables
library(sjstats)   # ICC - intraclass-correlation coefficient
library(MASS)
library(r2glmm)

#read in data
df <- read.csv("titanic.csv")

#explore data
View(df)
head(df)
str(df)

#change variables to factor
df_new <- df %>%
  mutate(pclass = factor(pclass),
         survived = if_else(survived == 1, "no", "yes"),
         survived = factor(survived, levels = c("no", "yes")),
        Gender= if_else(Gender == 0, "male", "female"),
         Gender= factor(Gender, levels = c("male", "female")))

head(df_new)

#checking missing values
df_new %>%
  summarise_each(list(~sum(is.na(.)))) %>%
  gather() # 263 NA's in age


list(df_new$age)

#remove missing values
df_clean<- df_new %>% 
  drop_na(age)

df_clean %>%
  summarise_each(list(~sum(is.na(.)))) %>%
  gather() # 

#sample size after removing data

df_clean %>% 
  summarise(n = n()) #1046

#Number of survived by gender, class

df_clean %>%
  group_by(Gender) %>%
  count(survived)

df_clean %>%
  group_by(pclass) %>%
  count(survived)

#logit - multiple regression
logit.m1 <- glm(survived ~ pclass + 
                Gender, data = df_clean, 
              family = binomial(link = "logit"))

#stepwise selection
logit.step <- stepAIC(logit.m1, direction = "both")

logit.step$anova


# multicollinearity
car::vif(logit.m1)

#model2 - interaction
logit.m2 <- glm(survived ~ pclass + Gender + pclass: 
                Gender, data = df_clean, 
              family = binomial(link = "logit"))
summary(logit.m2)


#AIC
anova(logit.m1, logit.m2)

# multicollinearity
car::vif(logit.m2)

#random intercept model

logit.mx1 <- glmer(survived ~ pclass + Gender + pclass:Gender
                  + (1 | age),
                  family = binomial(link = "logit"), 
                  data = df_clean )
summary(logit.mx1)


#does not violate multicolinearity
car::vif(logit.mx2)

#interaction is significant and should be included in the model
#R(m)2, the proportion of variance explained by the fixed predictors. 
r2.mx = r2beta(logit.mx2, method = 'nsj', partial = TRUE)
r2.mx

#model validation
logit.mxV <- glmer(survived ~ 1 
                   + (1 | age),
                   family = binomial(link = "logit"), 
                   data = df_clean )

performance::icc(logit.mxV)## suggests that random intercept of age does not explain that much variation in model
MuMIn::r.squaredGLMM(logit.mx1)

anova(logit.mx1,logit.mxV, test ="Chisq")

#pseudo r-squared for GLM
MuMIn::r.squaredLR(logit.m2)

#Controlling for age as a random factor does not improve model fit and is not needed in the model
#Therefore the best model is a logistic multiple regression (logit.m2)

#multiple comparisons for simple logistic multiple regression
tab_model(logit.m2, show.aic = T)
emmeans(logit.m2, pairwise ~ pclass | Gender, adjust = "bonferroni")$contrasts 
emmeans(logit.m2, pairwise ~ pclass:Gender)

#visualize
plot(allEffects(logit.m2))

#model table for mixed model to see ICC etc.
tab_model(logit.mx1, show.aic = T)


#How well does the model classify - model validation bonus
Pred <- predict(logit.m2, type = "response")
Pred <- if_else(Pred > 0.5, 1, 0)
ConfusionMatrix <- table(Pred, pull(df_clean, survived)) #`pull` results in a vector
#correct classification rate
sum(diag(ConfusionMatrix))/sum(ConfusionMatrix)#model correctly classifies 78%
ConfusionMatrix     

```


# Other

## Other (Optional)

<!-- If there is any additional information that you feel needs to be included in your preregistration, please enter it here. Literature cited, disclosures of any related work such as replications or work that uses the same data, or other context that will be helpful for future readers would be appropriate here. -->

Enter your response here.

# References

## 

```{=tex}
\vspace{-2pc}
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{-1in}
\setlength{\parskip}{8pt}
```
\noindent
